[project]
name = "phishing-detection-with-bert-preprocessing"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
readme = "README.md"
dependencies = [
    "fastapi>=0.141.0",
    "ipykernel>=7.3.0",
    "joblib>=1.5.3",
    "keras>=3.15.0",
    "keras-hub>=0.19.0",
    "matplotlib>=3.11.0",
    "numpy>=2.5.0",
    "pandas>=3.0.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.0",
    "tensorflow[and-cuda]==2.20.0",
    "tensorflow-text>=2.20.1",
    "transformers>=5.14.0",
    "beautifulsoup4>=4.15.0",
    "starlette>=1.3.1",
]
